apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.application.name }}-service
  labels:
    app: {{ .Values.application.name }}
spec:
  ports:
    - port: {{ .Values.application.servicePort }}
      targetPort: {{ .Values.application.port }}
      name: http
  selector:
    app: {{ .Values.application.name }}